extern const GeoLayout thwimp_geo[];
extern u8 thwimp_thwomp_surface_rgba16_ci8[];
extern u8 thwimp_thwomp_surface_rgba16_ci8_pal_rgba16[];
extern u8 thwimp_NSMBU_Thwimp_Model__1__ci8[];
extern u8 thwimp_NSMBU_Thwimp_Model__1__ci8_pal_rgba16[];
extern Vtx thwimp_thwimp_mesh_layer_1_vtx_0[80];
extern Gfx thwimp_thwimp_mesh_layer_1_tri_0[];
extern Vtx thwimp_thwimp_mesh_layer_1_vtx_1[4];
extern Gfx thwimp_thwimp_mesh_layer_1_tri_1[];
extern Vtx thwimp_thwimp_mesh_layer_1_vtx_2[40];
extern Gfx thwimp_thwimp_mesh_layer_1_tri_2[];
extern Gfx mat_thwimp_f3d_material_001[];
extern Gfx mat_revert_thwimp_f3d_material_001[];
extern Gfx mat_thwimp_f3d_material_002[];
extern Gfx mat_revert_thwimp_f3d_material_002[];
extern Gfx mat_thwimp_f3d_material_003[];
extern Gfx thwimp_thwimp_mesh_layer_1[];
extern Gfx thwimp_material_revert_render_settings[];
