extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_thwomp_surface_rgba16_ci8[];
extern u8 bob_dl_thwomp_surface_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_thwomp_face_rgba16_rgba16[];
extern u8 bob_dl__11_ci8[];
extern u8 bob_dl__11_ci8_pal_rgba16[];
extern u8 bob_dl_smgtile64_i8[];
extern u8 bob_dl_Tile0347_RGB_ci8[];
extern u8 bob_dl_Tile0347_RGB_ci8_pal_rgba16[];
extern Vtx bob_dl_bigThwomp_mesh_layer_1_vtx_0[56];
extern Gfx bob_dl_bigThwomp_mesh_layer_1_tri_0[];
extern Vtx bob_dl_bigThwomp_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_bigThwomp_mesh_layer_1_tri_1[];
extern Vtx bob_dl_leftSide_mesh_layer_1_vtx_0[96];
extern Gfx bob_dl_leftSide_mesh_layer_1_tri_0[];
extern Vtx bob_dl_rightSide_mesh_layer_1_vtx_0[321];
extern Gfx bob_dl_rightSide_mesh_layer_1_tri_0[];
extern Vtx bob_dl_startPlatform_mesh_layer_1_vtx_0[34];
extern Gfx bob_dl_startPlatform_mesh_layer_1_tri_0[];
extern Vtx bob_dl_waterArea_mesh_layer_1_vtx_0[467];
extern Gfx bob_dl_waterArea_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_body[];
extern Gfx mat_revert_bob_dl_body[];
extern Gfx mat_bob_dl_face[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_revert_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_greenCheckers[];
extern Gfx mat_bob_dl_waterArea[];
extern Gfx mat_revert_bob_dl_waterArea[];
extern Gfx bob_dl_bigThwomp_mesh_layer_1[];
extern Gfx bob_dl_leftSide_mesh_layer_1[];
extern Gfx bob_dl_rightSide_mesh_layer_1[];
extern Gfx bob_dl_startPlatform_mesh_layer_1[];
extern Gfx bob_dl_waterArea_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
